#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"
udo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow "Nginx HTTP"

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx restart
